import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomHeader from "./components/CustomHeader/CustomHeader";
import localFont from "next/font/local";

const stratos = localFont({
  variable: "--font-stratos",
  src: [
    {
      path: "../../public/fonts/stratos/stratosweb-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/stratos/stratosweb-bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${stratos.variable} antialiased`}
      >
        <CustomHeader />
        {children}
      </body>
    </html>
  );
}
